### ISSUE TITLE
Request for Data and Training Code Release 

### ISSUE THREAD

**Issue by RavenKang** [minhmanho/deep_preset#2]
I am very excited and pretty interested in the results of your project.
May I ask ... will you be able to release your training code and datasets?

**Comment by minhmanho** [comment]
Hi,

Thank you for asking.
I'm glad to hear that.
You can find a way of generating dataset at https://github.com/minhmanho/deep_preset#regarding-training-data
Regarding the training code, unfortunately, I have paused my research for a while to take care of other things.
Since there are many requests for it, I'm trying my best to publish the training code and Lightroom Add-On as soon as possible.
Please subscribe the repo and stay tuned :D
