### ISSUE TITLE
convergence of preset loss

### ISSUE THREAD

**Issue by oferidan1** [minhmanho/deep_preset#5]
hi, 
thanks for your great paper and code.
I noticed in the paper you add comaprison of L1 on preset estimtation with and without preset pair-wise loss.
according to the plot in the paper, also with PPL the preset estimation seem flat (value ~ 0.129) and doesnt go down too much.
is this the expected result? 
Thanks,
Ofer

![image](https://user-images.githubusercontent.com/70523006/152327102-94bd0098-b3d5-4b6b-8c62-a1219caee3f6.png)

**Comment by minhmanho** [comment]
Hi Ofer,

Thank you, and thank you so much for your question.
It is not the ideal result but the expected result.
The idea of PPL is to minimize distances between photos adjusted by the same preset in latent space.
(Regardless of image content, the model should infer a consistent preset and a color style representation vector from photos adjusted by the same preset.)
This will enhance not only the **stability of preset prediction** but also the direct color style transfer.

Best regards,
Man

**Comment by oferidan1** [comment]
Hi Man,
Thanks for your feedback.
Let me clarify my question:
I understand the idea of PPL loss, but according to the graph in the paper,
it seems that even with PPL loss the "preset estimation loss" looks flat
and not decreasing too much.
Usually, loss should decrease over time.
Did you notice this?
Thanks,
Ofer

**Comment by minhmanho** [comment]
Hi Ofer,

Yes, I noticed that. The ideal result is that the preset loss is decreased gradually.
However, estimating an exact preset (predicting accurate settings) for the actual color transformation is a tough problem, as shown by not-good convergences in the Figure.
Hence, I do not expect an accurate preset prediction because it is much easier to learn color style representation and directly transfer the color style using convolution.

Nevertheless, estimating presets seems more suitable for end-users because we can understand color transformation via predicted settings and subsequently adjust the color style.
For a better convergence of preset loss, I think the architecture and training framework should be re-designed so that the model can focus more on estimating presets.
I didn't train the preset prediction independently but I think it could help.

Best regards,
Man

**Comment by oferidan1** [comment]
Thanks for the feedback!
